---
- hosts: all
  become: yes
  
  tasks:
    - name: update package repo
      ansible.builtin.command: apt update
  
    - name: install nginx
      ansible.buitin.command: apt install nginx -y
    
    - name: install curl
      ansible.builtin.command: apt install curl -y
  
    - name: download node source
      ansible.builtin.shell: https://deb.nodesource.com/setup_14.x | -E bash -
  
    - name: install nodejs
      ansible.builtin.command: apt install -y nodejs

    -name: remove local repo
     ansible.builtin.shell: rm -rf /var/www/html
  
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/AzubiAfrica/Mobalysis.git
        dest: /var/www/html
	clone: yes
	update: yes
  
    - name: install node modules
      ansible.builtin.command: npm install
      args:
        chdir: /var/www/html/Mobalysis/frontend
  
    - name: run build
      ansible.builtin.command: npm run build
      args:
        chdir: /var/www/html/Mobalysis/frontend
  
    - name: copy contents to build directory
      ansible.builtin.shell: cp -r /var/www/html/Mobalysis/frontend/build/* /var/www/html
  
    - name: remove nginx default index file
      ansible.builtin.command: rm -rf index.nginx.debian.html
      args:
        chdir: /var/www/html
  
    - name: restart nginx
      ansible.builtin.command: systemctl restart nginx

...
